### ISSUE TITLE
web-plugin-packager releases

### ISSUE THREAD

**Issue by hythloda** [deephaven/deephaven-core#2032] opened 2022-02-25 15:45 UTC
**Description**

docker/web-plugin-packager/README.md references `FROM ghcr.io/deephaven/web-plugin-packager:latest`

there is no latest release. 
need to create latests or change README to reference main

**Steps to reproduce**

**Expected results**

**Actual results**

A clear and concise description of what actually happened.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by hythloda** [comment] 2022-02-25 15:47
Readme should also maybe contain:
`docker-compose up --build `

**Comment by mofojed** [comment] 2022-09-07 19:10
Dupe of #2033

**Closed by mofojed** 2022-09-07 19:10 UTC
Labels: bug, triage
