### ISSUE TITLE
Enable TLS support when making a pydeephaven's Session

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#3927] opened 2023-06-04 23:47 UTC
Currently a session only connects to the server via. a gRPC insecure_channel, we need to enable it to use gRPC secure_channel for better communication security.

**Comment by devinrsmith** [comment] 2023-06-05 04:19
Dupe of https://github.com/deephaven/deephaven-core/issues/3228

**Closed by devinrsmith** 2023-06-05 04:19 UTC
Labels: feature request, triage
