### ISSUE TITLE
Copy Selection* menu options are copying the entire table not just the selection.

### ISSUE THREAD

**Issue by staceybrusco** [deephaven/deephaven-core#1225] opened 2021-09-08 18:37 UTC
**Description**

Copy Selection or Copy Selection w/Headers is copying the entire table regardless of the selection.  I tried this via the right click menu option and using "command+c".

**Steps to reproduce**
1. Use the following query:

qq = emptyTable(100).update("Val = i", "Val10 = Val%10", "Val100 = Val%100")
groupy = qq.by("Val10")

2. Using the groupy table, highlight a few rows.
3. Right click on the selection and choose Copy Selection/Copy Selection w/Headers.
4. Paste the copied text into any editor.

**Expected results**

Only the highlighted rows should've been copied.

**Actual results**

The entire table is being copied.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: Groovy
 - OS: Mac Big Sur 11.5.2
 - Browser: Chrome Version 93.0.4577.63 (Official Build) (x86_64)
 - Docker: 4.0.0
<img width="1206" alt="Screen Shot 2021-09-08 at 2 31 18 PM" src="https://user-images.githubusercontent.com/84403742/132565978-12b29211-0d20-40ee-a86c-913af3945427.png">

**Comment by rcaudy** [comment] 2021-09-08 19:05
Duplicate of #1039 per @niloc132

**Closed by rcaudy** 2021-09-08 19:05 UTC
Labels: bug, triage
