### ISSUE TITLE
Error when sorting `StringSet` in the UI

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#1914] opened 2022-02-01 16:03 UTC
`StringSet`s causes an error when it is sorted in the UI.  If we can't sort it, we shouldn't let users try to sort it.

This query can be used to illustrate the problem:
```python
from deephaven.TableTools import emptyTable

ArrayStringSet = jpy.get_type("io.deephaven.stringset.ArrayStringSet")

values = ["A", "B", "C"]

def to_string_set() -> ArrayStringSet:
    """ Converts an iterable to a string set. """
    # print("HERE")
    return ArrayStringSet(values)


# t = emptyTable(10).update("SS = (io.deephaven.stringset.StringSet)to_string_set()")
# m = t.getMeta()

import threading
from time import sleep
import deephaven.Types as dht
from deephaven import DynamicTableWriter
from deephaven.conversion_utils import NULL_DOUBLE

dtw = DynamicTableWriter(["A","B"],[dht.int32, dht.stringset])

def populate():
    for i in range(1000):
        dtw.logRow([i, to_string_set()])

thread = threading.Thread(target=populate)
thread.start()

t1 = dtw.getTable()
t2 = t1.lastBy("A")
t3 = t1.naturalJoin(t2,"A", "C=B")
```

You get an error like:
```
heduler-Concurrent-4 | i.d.s.s.SessionState      | Internal Error '2fa7ff88-ec61-43d7-9588-ecf2a74af77b' io.deephaven.base.verify.RequirementFailure: Requirement failed: required Comparable.class.isAssignableFrom(sortColumns[ii].getType()) || sortColumns[ii].getType().isPrimitive(), instead sortColumnNames[ii] == "B", sortColumns[ii].getType() == class io.deephaven.engine.table.impl.preview.DisplayWrapper.
        at io.deephaven.base.verify.Require.fail(Require.java:108)
        at io.deephaven.base.verify.Require.requirement(Require.java:169)
        at io.deephaven.base.verify.Require.requirement(Require.java:175)
        at io.deephaven.engine.table.impl.SortOperation.<init>(SortOperation.java:54)
        at io.deephaven.engine.table.impl.QueryTable.sort(QueryTable.java:2369)
        at io.deephaven.server.table.ops.SortTableGrpcImpl.create(SortTableGrpcImpl.java:98)
        at io.deephaven.server.table.ops.SortTableGrpcImpl.create(SortTableGrpcImpl.java:21)
        at io.deephaven.server.table.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:461)
        at io.deephaven.server.table.TableServiceGrpcImpl.lambda$batch$5(TableServiceGrpcImpl.java:313)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:847)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:143)
        at java.lang.Thread.run(Thread.java:829)
```

**Comment by mofojed** [comment] 2022-02-02 19:37
@niloc132 is there a way for the API to tell if a column is sortable? Or is this something that should be fixed in the engine?

**Comment by niloc132** [comment] 2022-02-02 19:43
Two issues here, one bug, one feature request.

The bug is https://github.com/deephaven/deephaven-core/issues/1871 (or adjacent), we shouldnt be logging this error, we should only pass the error message back to the client API to tell the UI. This is what DHE does.

The feature request here is that we would like the server to send as column metadata that the column isn't sortable.

**Comment by nbauernfeind** [comment] 2022-09-01 14:54
This is a duplicate of #1339; the UI's DisplayWrapper is not sortable. Disabling the sort sounds better than allowing DisplayWrappers to be sorted (what I propose in the other ticket). Sorting all rows after toString()'ing an object is dangerous as the toString() may mutate  without a proper table update (behavior depends on the real type of the column and how those objects are manipulated).

It would be rather trivial to add an attribute to each column that is sortable. Such as `deephaven:sortable` would be `true` and otherwise omitted.

**Comment by mofojed** [comment] 2023-06-19 20:32
@ethanalvizo was looking at adding attributes for databars #3549 , this may be a simpler one to get his feet wet and see how to implement an attribute end-to-end.

**Comment by dsmmcken** [comment] 2023-06-20 14:05
Yeah, `restrict_sort_to `  should also probably set this.

**Closed** 2023-06-29 20:07 UTC
Labels: bug
