### ISSUE TITLE
Unable to scroll s3 parquet file

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/deephaven-core#6423] opened 2024-11-22 23:29 UTC
Attempting to view a parquet file from s3, I am unable to scroll the resulting table.

![cant_scroll](https://github.com/user-attachments/assets/47fb8b3e-9541-4631-b8e1-0531ef7fa1be)

Steps to reproduce:

1. Run this code
```py
from deephaven import parquet
from deephaven.experimental import s3

poi = parquet.read(
    path="s3://fsq-os-places-us-east-1/release/dt=2024-11-19/places/parquet/places-00000.snappy.parquet",
    special_instructions=s3.S3Instructions(
        # @devinrsmith had a theory that it was timeout, but that doesn't seem to make a difference
        connection_timeout="PT20s",
        read_timeout="PT20s"
    ),
)
```

2. Attempt to scroll the resulting table in the UI

Note: reversing the table and scrolling DOES work. No idea why.

Versions:
Issue was observed on both these commit
acdb6bfb47baa103c929797b610270f09e551214
7b47794a0739671d1de933836bd69f191a3ce66f

**Comment by niloc132** [comment] 2024-11-24 17:52
I'm observing a few odd behaviors that are worth looking into, but all seem to predate both the recent viewport work and the last web version bump.

 * The issue mentioned in the description - I can also get this by selecting a row and just holding the down arrow, so as to move the viewport apparently one row at a time. Logging actual calls to setViewport and updated events from the table, it appears that the viewport jumps about 3 rows at a time (some debouncing) with each update having the expected offset and a constant number of rows, and no sizechanged events. As it predates the viewport change and doesn't _appear_ to be based on the data coming back from the server, I'm leaning towards suggesting that this is a UI bug that might be timing related.
 * When I first run the query, it takes about 12s for the command to return from the server. It takes much longer than that to get the viewport back from the server - I usually get impatient and stop waiting for it, close the panel, and reopen it. I _believe_ that after that 12s for the one partition we should already have the data in memory, but maybe we have to go back to s3 to get the actual data?
 * If I get impatient and close it, sometimes when I click it again and go back to waiting, the grid in the UI no longer has the columns, just a loading screen. In those situations, I can run `print(1)` commands in the console and not see the results, though the command returns immediately. Further, the server log shows the print result immediately, indicating that this is not an exclusive lock or serial thread contention issue. Once the table's columns and contents appear, the log messages do too.

This appears to predate the viewport cleanup work, it is still present as far back as 08c596d6133.

**Comment by niloc132** [comment] 2024-11-25 16:18
Thanks to @mofojed's help, the main bug here was introduced by #5890 - while we no longer re-create streams to the server when the viewport changes, we do change some internal state, and for uncoalesced tables we can end up exposing that "I don't know what the size of this table is" size to the UI when that happens. The fix is to check for both "the subscription is active" states when deciding if we the subscription for the authoritative source of the table size.

Note that this applies for non-uncoalesced tables as well, but it is much more of an edge case there, where the size could change separately from barrage subscription messages.

I will triage the other bugs discovered here into their own separate issues.

**Comment by niloc132** [comment] 2024-11-27 19:22
https://github.com/deephaven/deephaven-core/issues/6435 is the root cause of the other two issues I was experiencing.

**Closed** 2024-12-05 22:14 UTC
Labels: bug, triage
