### ISSUE TITLE
Parquet Read/Write Spams Log Output

### ISSUE THREAD

**Issue by stanbrub** [deephaven/deephaven-core#5076] opened 2024-01-26 19:00 UTC
Some compression codecs print many unnecessary lines of log output to the console/log when reading or writing parquet.  The message typically looks something like `deephaven-1  | 2024-01-26T18:07:45.116Z | ializationExecutor-6 |  INFO | o.a.h.i.c.CodecPool       | Got brand-new decompressor [.zst]`

There is no apparent usefulness in printing thousands of the same log message and this could be slowing things down for some codecs when logs and parquet read/write are competing for file system access.  

- Having a message about the compression/decompression codec is useful for debugging
- GZip read is printing the wrong message `Got brand-new decompressor [.zst]`

Below is a table that shows the bytes output during read/write operations for the codecs being testing in Benchmark. The smaller ones are fine, since there will naturally be _some_ log output.

```
Benchmark Test Name	Log Bytes
writeMultiColSnappy	  125,319
readMultiColSnappy	  126,417 
writeMultiColZstd	  125,488  
readMultiColZstd	7,664,411
writeMultiColLzo	  125,527 
readMultiColLzo		8,017,209
writeMultiColLz4Raw	  126,637
readMultiColLz4Raw	  145,764 
writeMultiColGzip	7,534,831 
readMultiColGzip	7,620,551
writeMultiColNone	  125,364
readMultiColNone	  123,315
```

**Comment by rcaudy** [comment] 2024-01-26 20:32
Duplicate of part of https://github.com/deephaven/deephaven-core/issues/2920

**Closed** 2024-01-26 20:32 UTC
Labels: bug, triage, NoDocumentationNeeded, NoReleaseNotesNeeded
