### ISSUE TITLE
Manage Custom Columns is not working

### ISSUE THREAD

**Issue by staceybrusco** [deephaven/deephaven-core#1223] opened 2021-09-08 17:32 UTC
**Description**

Manage Custom Columns is not working when adding a new column and setting its value to an existing column.

**Steps to reproduce**
1. Use the following query:
```groovy
complexTicking = timeTable("00:00:01").update(
 "MyString=new String(`a`+i)",
 "MyInt=new Integer(i)",
 "MyLong=new Long(i)",
 "MyDouble=new Double(i+i/10)",
 "MyFloat=new Float(i+i/10)",
 "MyBoolean=new Boolean(i%2==0)",
 "MyChar= new Character((char) ((i%26)+97))",
 "MyShort=new Short(Integer.toString(i%32767))",
 "MyByte= new java.lang.Byte(Integer.toString(i%127))")
.update(
 )
.formatColumns("MyInt=Decimal(`0,000`)", "MyInt=GREEN")
.formatColumns("MyLong=Decimal(`00,000`)", "MyLong=RED")
.formatColumns("MyDouble=Decimal(`#,000.00 ZZZ`)", "MyDouble=YELLOW")
.layoutHints("autofilter=MyString,MyInt,MyDouble,MyFloat,MyBoolean")
```
2. From the complexTickingTable, select the Table Options menu on the right.
3. Select Manage Custom Columns
4. Fill in the desired TableName (I used Test) and the Column Formula (I used ANY of the column names, but let's take MyFloat for now).
5. Click on 'Save Column'

**Expected results**

There should be a new column titled "Test", and it should be identical to the existing "MyFloat" column.

**Actual results**

The "Test" column is created, but it's empty.  I've tried this multiple times with every column type, and nothing seems to be populating the new column with values.  Additionally, sometimes the function will just spin in a state of "Applying".

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

<img width="1527" alt="Screen Shot 2021-09-08 at 12 48 51 PM" src="https://user-images.githubusercontent.com/84403742/132556798-77b68fb3-3a06-4260-8e16-6617b4a5e693.png">
<img width="1655" alt="Screen Shot 2021-09-08 at 1 30 36 PM" src="https://user-images.githubusercontent.com/84403742/132556800-428885bc-dc3d-487d-89ab-a4185556895d.png">

**Versions**
 - Deephaven: Groovy
 - OS: Mac - Big Sur 11.5.2
 - Browser: Chrome Version 93.0.4577.63 (Official Build) (x86_64)
 - Docker: 4.0.0

**Comment by niloc132** [comment] 2021-12-30 17:00
This seems to work now, will test older versions to be sure I am reproducing the issue properly before closing it out.

**Comment by niloc132** [comment] 2022-01-03 20:54
The stack trace appears to be the same as https://github.com/deephaven/deephaven-core/issues/1250, and I also cannot reproduce in versions as old as 0.5.3. Also cannot reproduce in 0.8.0 or latest.

**Closed by niloc132** 2022-01-03 20:54 UTC
Labels: bug
