### ISSUE TITLE
EPIC: Java API supporting connection to remote worker + simple table ops

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-core#657] opened 2021-05-24 19:07 UTC
As a user I want to write a stand-alone java program that connects to a remote worker and executes some simple table operations - such as NewTable, where, sort.

**Comment by rcaudy** [comment] 2021-05-24 19:19
Duplicate of https://github.com/deephaven/deephaven-core/issues/257

**Comment by nbauernfeind** [comment] 2021-09-17 21:38
This work is completed by #953.

**Closed by nbauernfeind** 2021-09-17 21:38 UTC
Labels: epic, java-api-basic
