### ISSUE TITLE
`lastBy` produces garbage values

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#1916] opened 2022-02-01 17:15 UTC
See the query below.  It produces a table of ints and stringsets.  When last by is applied, the stringset column starts with garbage values.

The problem is observed in 0.9.0.

```

from deephaven.TableTools import emptyTable

ArrayStringSet = jpy.get_type("io.deephaven.stringset.ArrayStringSet")

values = ["A", "B", "C"]

def to_string_set() -> ArrayStringSet:
    """ Converts an iterable to a string set. """
    # print("HERE")
    return ArrayStringSet(values)


# t = emptyTable(10).update("SS = (io.deephaven.stringset.StringSet)to_string_set()")
# m = t.getMeta()

import threading
from time import sleep
import deephaven.Types as dht
from deephaven import DynamicTableWriter
from deephaven.conversion_utils import NULL_DOUBLE

dtw = DynamicTableWriter(["A","B"],[dht.int32, dht.stringset])

def populate():
    for i in range(1000):
        dtw.logRow([i, to_string_set()])

thread = threading.Thread(target=populate)
thread.start()

t1 = dtw.getTable()
t2 = t1.lastBy("A")
t3 = t1.naturalJoin(t2,"A", "C=B")
t2m = t2.getMeta()
```

![image](https://user-images.githubusercontent.com/5250374/152017082-5d7c707e-b1bf-47cd-b649-9653fb868a7d.png)
![image](https://user-images.githubusercontent.com/5250374/152016704-d15cf5ac-0a35-4f36-a5a1-3bbdba89019d.png)
![image](https://user-images.githubusercontent.com/5250374/152016917-b684afc2-db4e-463f-b90f-81d9b61daf7c.png)

**Comment by chipkent** [comment] 2022-02-01 17:21
Here is a better `t2` screenshot.
![image](https://user-images.githubusercontent.com/5250374/152018115-90d40b23-d4a9-45a6-abcd-d77817b1ea8f.png)

**Comment by niloc132** [comment] 2022-02-01 19:31
Can't reproduce at this time, closing for now.

**Closed by niloc132** 2022-02-01 19:31 UTC
Labels: bug, triage
