### ISSUE TITLE
Hovering over a column name in the web UI shows "UnsupportedOperationException" instead of the number of rows.

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#966] opened 2021-08-04 04:49 UTC
![priceToolTipUnsupportedOpEx](https://user-images.githubusercontent.com/37232625/128123741-77872dfc-7eb6-452a-9d1a-00a75b200cc4.png)

**Comment by dsmmcken** [comment] 2021-08-04 13:24
duplicate of #931 and https://github.com/deephaven/web-client-ui/pull/137

**Closed by dsmmcken** 2021-08-04 13:24 UTC
Labels: bug, release blocker, triage
