### ISSUE TITLE
Server shutdown: Unexpected iteration job error

### ISSUE THREAD

**Issue by viper1** [deephaven/deephaven-core#4714] opened 2023-10-25 00:39 UTC
Hello,

I have been running into this server error pretty regularly when the PC is under load:
Server shutdown: Unexpected iteration job error
The exception is usually complaining about the reference count being out of order (java.lang.IllegalStateException: IterationManager-1423254110's reference count has been decreased more than increased)

It seems to be related to #4063, #4473, #4358, #4391 so I was looking forward to trying v0.29 with the fix for #4473, but it happened immediately on startup. Full stack trace below. 

How to replicate: There is no pattern that I can discern. It happens somewhat randomly. 
1. incoming real-time data via wss/rest/sql
2. anywhere from tens to a few thousand rows every second, reasonably straightforward 5-20 columns. 
3. the computations are chained simple formulas (add/multiply/create new columns), update_by, agg_by.
4. it does seem to happen more with cumsum ops. 
5. it happens more often when the pc is under heavy load. perhaps the compute is getting past the UGP boundary and then things fall apart? 
6. it happens VERY often when sharing tables using uri's between two deephaven instances (on the same machine). This is probably the easiest way to replicate. 
7. it doesn't happen on blink tables, only on append tables. 
8. doesn't seem related to size of the append table (can happen with 1k rows right at startup or 500k+ rows)

The best way to replicate might be on a PC/server under some stress (atleast half the at cores 50%+ usage), chain a bunch of update_by/agg_by on some streaming data, maybe use URI's between two deephaven instances to split the computations and you should see it happen. 

Full stack:

Server shutdown: Unexpected iteration job error
java.lang.IllegalStateException: IterationManager-1423254110's reference count has been decreased more than increased
io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:218)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onTaskError(JobScheduler.java:175)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:283)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:256)
io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1322)
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1373)
io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1911)
org.jpy.PyLib.callAndReturnObject(Native Method)
org.jpy.PyObject.call(PyObject.java:449)
io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
java.base/java.lang.Thread.run(Thread.java:833)

v0.26 all the way through v0.29.1, running on ubuntu/docker

**Comment by rcaudy** [comment] 2023-10-25 01:04
Thanks for the report. We thought this was entirely fixed a few releases prior. We'll investigate update_by, but if you have any additional logs or stack traces, please share them here.

**Comment by viper1** [comment] 2023-10-25 02:16
A few more lines in the docker log, but it looks like the exception got truncated. 

Initiating shutdown due to: Unexpected iteration job error
java.lang.IllegalStateException: IterationManager-1423254110's reference count has been decreased more than increased
	at io.deephaven.util.referencecounting.ReferenceCounted.decrementReferenceCount(ReferenceCounted.java:218)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.onTaskError(JobScheduler.java:175)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:283)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.execute(JobScheduler.java:256)
	at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager.lambda$startTasks$0(JobScheduler.java:161)
	at io.deephaven.engine.table.impl.util.UpdateGraphJobScheduler$1.run(UpdateGraphJobScheduler.java:41)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph.runNotification(PeriodicUpdateGraph.java:1322)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$ConcurrentNotificationProcessor.processSatisfiedNotifications(PeriodicUpdateGraph.java:1373)
	at io.deephaven.engine.updategraph.impl.PeriodicUpdateGraph$NotificationProcessorThreadFactory.lambda$newThread$0(PeriodicUpdateGraph.java:1911)
	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.call(PyObject.java:449)
	at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: io.deephaven.base.verify.AssertionFailure: Assertion failed: asserted closed == false, instead closed == true.
		at io.deephaven.base.verify.Assert.fail(Assert.java:100)
		at io.deephaven.base.verify.Assert.eqFalse(Assert.java:1022)
		at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.close(JobScheduler.java:288)
		at io.deephaven.engine.table.impl.util.JobScheduler$IterationManager$TaskInvoker.reportError(JobScheduler.java:282)
		... 10 more

**Comment by rcaudy** [comment] 2023-10-25 14:39
Sounds like you're able to reproduce this relatively easily. What I'm really hoping to capture is a root cause stack trace; that is, what caused us to deliver a task error? That way we can fix or consult on the cause of the error, and hopefully get a clue about the double-close as well.

**Comment by rcaudy** [comment] 2023-10-25 15:26
@viper1 , the stack traces you provided appear to line up with an older version of Deephaven, specifically any version between 0.26.0 and 0.27.1.

We believe we fixed the issue you're seeing in 0.28.0, and we're now on 0.29.1.

If you'd like us to investigate further, please provide a stack trace against 0.29.1.

**Comment by viper1** [comment] 2023-10-25 18:07
This might be user error. It seems the container wasn't rebuilt after updating the version to 29.1. Getting a parse_instant error on startup so it looks like the api might have changed. I will try to reproduce on 29 over the next few days/this weekend. 
Feel free to close if needed.

**Comment by rcaudy** [comment] 2023-10-25 18:46
I think you're likely running into some changes that were made to eliminate most of Deephaven's Python time library, since it was a dissatisfying wrapper around Java time types that could lead to confusion and potentially poor performance when used in UDFs.

We've standardized on offering simple conversion functions between Java and Python time types.

**Comment by rcaudy** [comment] 2023-10-25 18:47
I'll close this issue for now, but it would be entirely appropriate to re-open if you can reproduce on 0.29.1. Please keep us updated regarding your testing, either here or via Slack (https://deephaven.io/slack).

**Closed** 2023-10-25 19:37 UTC
Labels: bug, query engine, core, user-reported
