### ISSUE TITLE
Get build versions for UI

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-core#1616] opened 2021-11-30 19:45 UTC
We'd like to display the core version (whatever that entails) in the settings panel like we do in enterprise. This version would also be exported with support logs to help make it easier for us to troubleshoot reports in the future. We currently display the web package version in the UI, but that could diverge from the core version in the future.

Add some way for the JS API or client to get info about the core it is running against so we can display and log that info as needed. In enterprise we have a build number, git sha, and java version. Whatever info the core team thinks would be useful for specifying what version a user is running.

**Comment by mofojed** [comment] 2022-08-17 14:34
Related to #2668 , we need some way of getting server information/configuration details.

**Comment by mofojed** [comment] 2022-08-17 18:27
Duplicate of #2390 , closing this one as that one has more implementation details.

**Closed by mofojed** 2022-08-17 18:27 UTC
Labels: feature request, triage
