### ISSUE TITLE
Unit test failure: ParquetTableReadWriteTest.testParquetZstdCompressionCodec

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2584] opened 2022-06-27 13:39 UTC
https://scans.gradle.com/s/6x67o57rj3m3y/tests/:extensions-parquet-table:testOutOfBand/io.deephaven.parquet.table.ParquetTableReadWriteTest/testParquetZstdCompressionCodec?top-execution=1

https://github.com/deephaven/deephaven-core/runs/7067039950?check_suite_focus=true#step:8:1373

```
io.deephaven.base.verify.RequirementFailure: Requirement failed: required isOpen == true, instead isOpen == false.	
at io.deephaven.base.verify.Require.fail(Require.java:107)	
•••
at io.deephaven.parquet.base.util.CachedChannelProvider$CachedChannel.size(CachedChannelProvider.java:174)	
•••
at io.deephaven.parquet.compress.DeephavenCodecFactory$CodecWrappingCompressor.decompress(DeephavenCodecFactory.java:108)	
at io.deephaven.parquet.base.ColumnPageReaderImpl.readDataPage(ColumnPageReaderImpl.java:221)	
at io.deephaven.parquet.base.ColumnPageReaderImpl.materialize(ColumnPageReaderImpl.java:90)	
at io.deephaven.parquet.table.pagestore.topage.ToPage.getResult(ToPage.java:58)	
at io.deephaven.parquet.table.pagestore.topage.ToPage.toPage(ToPage.java:85)	
at io.deephaven.parquet.table.pagestore.ColumnChunkPageStore.toPage(ColumnChunkPageStore.java:91)	
at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPage(VariablePageSizeColumnChunkPageStore.java:122)	
at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:161)	
at io.deephaven.parquet.table.pagestore.VariablePageSizeColumnChunkPageStore.getPageContaining(VariablePageSizeColumnChunkPageStore.java:20)	
•••
at io.deephaven.parquet.table.region.ParquetColumnRegionBase.getChunk(ParquetColumnRegionBase.java:38)	
•••
at io.deephaven.parquet.table.ParquetTableReadWriteTest.compressionCodecTestHelper(ParquetTableReadWriteTest.java:272)	
at io.deephaven.parquet.table.ParquetTableReadWriteTest.testParquetZstdCompressionCodec(ParquetTableReadWriteTest.java:296)	
•••
```

**Comment by niloc132** [comment] 2022-06-27 13:56
Closing as duplicate of https://github.com/deephaven/deephaven-core/issues/2569

**Closed by niloc132** 2022-06-27 13:56 UTC
Labels: bug, parquet
