### ISSUE TITLE
pydeephaven StatusCode.UNAUTHENTICATED, grpc_status:16 running on a remote server

### ISSUE THREAD

**Issue by viper1** [deephaven/deephaven-core#3337] opened 2023-01-20 01:34 UTC
Hello, 

I am unable to make any dh requests from a windows/python 3.8 client connecting to a remote server DH running on ubuntu/docker. The session connection seems to be made, but any subsequent calls error out. 
Connecting via the IDE from the same windows machine to the same remote server works fine. 

The python client errors are:

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = ""
	debug_error_string = "UNKNOWN:Error received from peer ipv4:192.168.0.108:10000 {created_time:"2023-01-20T01:25:51.754381319+00:00", grpc_status:16, grpc_message:""}"

and 

DHError: failed to finish TimeTableOp operation

Just wondering if this is user error on my side, or a possible bug? Happy to share version and debug info if that would help.

Thanks!

Python code:

from pydeephaven import Session
session = Session(host='192.168.0.108',port=10000,session_type='python') 
table = session.time_table(period=1000000000).update(formulas=["Col1 = i % 2"])

The session seems to be created fine, but the 3rd line errors out with the following stack trace:

Traceback (most recent call last):

  File "C:\Users\me\anaconda3\envs\py38_vbt\lib\site-packages\pydeephaven\_table_service.py", line 46, in grpc_table_op
    response = stub_func(op.make_grpc_request(result_id=result_id, source_id=table_reference),

  File "C:\Users\me\anaconda3\envs\py38_vbt\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)

  File "C:\Users\me\anaconda3\envs\py38_vbt\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = ""
	debug_error_string = "UNKNOWN:Error received from peer ipv4:192.168.0.108:10000 {created_time:"2023-01-20T01:25:51.754381319+00:00", grpc_status:16, grpc_message:""}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\me\AppData\Local\Temp\ipykernel_202656\3220424899.py", line 1, in <cell line: 1>
    session.time_table(period=1000000000).update(formulas=["Col1 = i % 2"])

  File "C:\Users\me\anaconda3\envs\py38_vbt\lib\site-packages\pydeephaven\session.py", line 283, in time_table
    return self.table_service.grpc_table_op(None, table_op)

  File "C:\Users\me\anaconda3\envs\py38_vbt\lib\site-packages\pydeephaven\_table_service.py", line 57, in grpc_table_op
    raise DHError(f"failed to finish {op.__class__.__name__} operation") from e

DHError: failed to finish TimeTableOp operation

**Comment by jmao-denver** [comment] 2023-02-22 20:04
@viper1 Thanks for trying DH Python client and sorry for not responding sooner.  i don't have a Windows machine to try your code but I just did it on my Mac with the latest pydeephaven and the server and couldn't reproduce the issue. Our suspicion is that the version of pydeephaven you were using was probably out of date due to the fact we had a long gap between the server release and the client release a couple of weeks ago.  Could you download the latest pydeephaven and see if that resolves the problem?

**Comment by viper1** [comment] 2023-02-22 23:01
Fixed in the new version. Thanks for checking and following up

**Comment by jmao-denver** [comment] 2023-02-23 18:31
The user reported  that it was fixed in the new version

**Closed** 2023-02-23 18:31 UTC
Labels: bug
