### ISSUE TITLE
Kafka consume stops short of all rows

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#3792] opened 2023-05-04 14:08 UTC
A user reported that a kafka/redpanda feed was not producing all of the rows, despite using `ALL_PARTITIONS_SEEK_TO_BEGINNING`. The data was created during a single trading day, into a single partition, and according to the redpanda console, there were 1,531,395 messages with 7 day retention and no byte limit, 656 MiB used.

Initially the user was running into https://github.com/deephaven/deephaven-core/issues/3617 with a date field, but changed that field to a string.

Saw 1,377,532 out of 1,531,395 messages according to the web UI table tooltip. It appears that all of the missing messages were at the end of the feed.

**Comment by rcaudy** [comment] 2023-05-04 14:23
Was the output table failed? (`Table.isFailed()` invoked on the Java `Table`)
The user should install a listener to capture failure.

**Comment by stanbrub** [comment] 2023-05-19 19:52
I've tried...
- Large data sets (500mm rows)
- Different memory settings for DH and Redpanda  (1G vs 32G)
- Wide rows (1000 columns)
- Wide columns (120 char strings)

Ingesting using _count_by_ are accurate every time.  But the viewport in the UI doesn't show all of the records.  The _row_count_ table shows the correct number of columns, but the _consumer_tbl_ "count" column, which is a column generated sequentially from 1, does not show the last records.  (And, yes, I've scrolled to the bottom of _consumer_tbl_)

Perhaps this is what they are seeing?  I don't know what their data looks like or what queries they are running, but this does look similar, though not as many rows are missing.

![32G-DH-RPanda-Viewport-Wrong](https://github.com/deephaven/deephaven-core/assets/120737309/e5aff336-3094-4ce8-8ec3-9974b7f315f2)

**Comment by devinrsmith** [comment] 2023-05-19 19:57
`consumer_table` here is a stream table, it shouldn't show all the rows (I'm surprised it's showing any... once the kafka stream has finishing replaying, I'd assume `consumer_tbl` would be empty). I'd assume if it's an append table, it shouldn't be missing any rows.

**Comment by stanbrub** [comment] 2023-05-19 19:59
So what exactly are they doing to tell that they are missing the end?

**Comment by devinrsmith** [comment] 2023-05-19 20:03
I believe they were looking at tooltip on an append table.

**Comment by stanbrub** [comment] 2023-05-19 20:15
If I do an "append" for the 2mm data, the _consumer_tbl_ has wrong/different tooltips for all the columns.  But the data appears to be there.  If I keep scrolling back and forth, top to bottom, the tool tips get fixed.

**Comment by niloc132** [comment] 2023-05-23 18:20
> `consumer_table` here is a stream table, it shouldn't show all the rows (I'm surprised it's showing any... once the kafka stream has finishing replaying, I'd assume `consumer_tbl` would be empty). I'd assume if it's an append table, it shouldn't be missing any rows.

Note that the JS API treats stream tables as if they are appending only, rather than removing rows, otherwise the data is visible too briefly to be useful in the majority of cases.

**Comment by stanbrub** [comment] 2023-05-23 20:03
I am unable to reproduce what I was seeing yesterday.  Should have recorded it then.  I was using a TableType.append() on 2 million records.  For now, it looks like this ticket is still "cannot reproduce".

**Comment by stanbrub** [comment] 2023-05-31 03:28
I was able to reproduce this.  Attached is a script used to reproduce against redpanda.  There's also some collected data for different message counts with all good date-times except one bad one.  

Here's what things look like:
- More rows than just the bad row and excluded from the table, even if the bad row is dead last
- If the bad row is in the middle of the data, subsequent rows are excluded
- TableType append() vs blink() have this same problem

[MissingKafkaConsumedRows.csv](https://github.com/deephaven/deephaven-core/files/11608307/MissingKafkaConsumedRows.csv)
[date-time-missing-kafka-consume-rows.txt](https://github.com/deephaven/deephaven-core/files/11608308/date-time-missing-kafka-consume-rows.txt)

**Comment by rcaudy** [comment] 2023-07-07 20:49
This was probably fixed by https://github.com/deephaven/deephaven-core/pull/4142.
There is a separate, but related issue, in https://github.com/deephaven/deephaven-core/issues/4148.
Closing for now, until/unless we have new reports.

**Closed by rcaudy** 2023-07-07 20:49 UTC
Labels: bug, triage, kafka

**Comment by stanbrub** [comment] 2023-07-08 00:32
**Is this what is now expected?**

I retested this issue with 0.26.0 and got the following when putting a single bad date at the end of 1 million good records.

Achieved a count of 897,856 records before the below error was displayed.  (The bad Instant string was literally "BAD DATETIME")

`````
ph-updateExecutor-13 | .AsyncClientErrorNotifier | Error in table update: io.deephaven.time.DateTimeUtils$DateTimeParseException: Cannot parse instant: BAD DATETIME

        at io.deephaven.time.DateTimeUtils.parseInstant(DateTimeUtils.java:3452)
        at io.deephaven.kafka.ingest.JsonNodeUtil.getInstant(JsonNodeUtil.java:743)
        at io.deephaven.kafka.ingest.JsonNodeUtil.getInstant(JsonNodeUtil.java:721)
        at io.deephaven.kafka.ingest.JsonNodeInstantFieldCopier.copyField(JsonNodeInstantFieldCopier.java:31)
        at io.deephaven.kafka.ingest.MultiFieldChunkAdapter.handleChunk(MultiFieldChunkAdapter.java:73)
        at io.deephaven.kafka.ingest.KafkaStreamPublisher.flushValueChunk(KafkaStreamPublisher.java:329)
        at io.deephaven.kafka.ingest.KafkaStreamPublisher.consumeRecords(KafkaStreamPublisher.java:281)
        at io.deephaven.kafka.KafkaTools$SimpleKafkaRecordConsumer.consume(KafkaTools.java:2365)
        at io.deephaven.kafka.ingest.KafkaIngester.pollOnce(KafkaIngester.java:354)
        at io.deephaven.kafka.ingest.KafkaIngester.consumerLoop(KafkaIngester.java:284)
        at java.lang.Thread.run(Thread.java:833)
caused by:
io.deephaven.time.DateTimeUtils$DateTimeParseException: Cannot parse zoned date time: BAD DATETIME
        at io.deephaven.time.DateTimeUtils.parseZonedDateTime(DateTimeUtils.java:3536)
        at io.deephaven.time.DateTimeUtils.parseInstant(DateTimeUtils.java:3450)
        at io.deephaven.kafka.ingest.JsonNodeUtil.getInstant(JsonNodeUtil.java:743)
        at io.deephaven.kafka.ingest.JsonNodeUtil.getInstant(JsonNodeUtil.java:721)
        at io.deephaven.kafka.ingest.JsonNodeInstantFieldCopier.copyField(JsonNodeInstantFieldCopier.java:31)
        at io.deephaven.kafka.ingest.MultiFieldChunkAdapter.handleChunk(MultiFieldChunkAdapter.java:73)
        at io.deephaven.kafka.ingest.KafkaStreamPublisher.flushValueChunk(KafkaStreamPublisher.java:329)
        at io.deephaven.kafka.ingest.KafkaStreamPublisher.consumeRecords(KafkaStreamPublisher.java:281)
        at io.deephaven.kafka.KafkaTools$SimpleKafkaRecordConsumer.consume(KafkaTools.java:2365)
        at io.deephaven.kafka.ingest.KafkaIngester.pollOnce(KafkaIngester.java:354)
        at io.deephaven.kafka.ingest.KafkaIngester.consumerLoop(KafkaIngester.java:284)
        at java.lang.Thread.run(Thread.java:833)
caused by:
java.lang.RuntimeException: No matching time zone: DATETIME
        at io.deephaven.time.DateTimeUtils.parseZonedDateTime(DateTimeUtils.java:3531)
        at io.deephaven.time.DateTimeUtils.parseInstant(DateTimeUtils.java:3450)
        at io.deephaven.kafka.ingest.JsonNodeUtil.getInstant(JsonNodeUtil.java:743)
        at io.deephaven.kafka.ingest.JsonNodeUtil.getInstant(JsonNodeUtil.java:721)
        at io.deephaven.kafka.ingest.JsonNodeInstantFieldCopier.copyField(JsonNodeInstantFieldCopier.java:31)
        at io.deephaven.kafka.ingest.MultiFieldChunkAdapter.handleChunk(MultiFieldChunkAdapter.java:73)
        at io.deephaven.kafka.ingest.KafkaStreamPublisher.flushValueChunk(KafkaStreamPublisher.java:329)
        at io.deephaven.kafka.ingest.KafkaStreamPublisher.consumeRecords(KafkaStreamPublisher.java:281)
        at io.deephaven.kafka.KafkaTools$SimpleKafkaRecordConsumer.consume(KafkaTools.java:2365)
        at io.deephaven.kafka.ingest.KafkaIngester.pollOnce(KafkaIngester.java:354)
        at io.deephaven.kafka.ingest.KafkaIngester.consumerLoop(KafkaIngester.java:284)
        at java.lang.Thread.run(Thread.java:833)
`````
