### ISSUE TITLE
Possible CSV parsing bug with missing columns

### ISSUE THREAD

**Issue by rcaudy** [deephaven/deephaven-core#2898] opened 2022-09-22 14:03 UTC
User report via Slack. https://deephavencommunity.slack.com/archives/C036HT73T43/p1663844212942279

Apparently attempts to read CSV's with fewer than expected columns in some rows are getting the following error message:
```
RangeError: offset is out of bounds
```

We should determine:
1. Was the error message by design, or a bug?
2. If by design, can we improve the error message?
3. If by design, is there a setting to get other behavior?

I've attached the user's reproducer (uncompressed, and zipped).
[errordata.csv](https://github.com/deephaven/deephaven-core/files/9626493/errordata.csv)
[errordata.csv.zip](https://github.com/deephaven/deephaven-core/files/9626494/errordata.csv.zip)

**Comment by rcaudy** [comment] 2022-09-22 15:24
User reported that this was a CSV upload from the web UI, rather than a Python read CSV.

**Comment by mofojed** [comment] 2022-10-07 15:02
Shortened the input CSV to just a few lines:


[errordata-short.csv](https://github.com/deephaven/deephaven-core/files/9734993/errordata-short.csv)

**Comment by mofojed** [comment] 2022-10-07 15:30
The problem is these chars are UTF-16, and cannot be parsed as UTF-8. GWT seems to only have support for UTF-8, the problematic line of code is: https://github.com/deephaven/deephaven-core/blob/main/web/client-api/src/main/java/io/deephaven/web/client/api/parse/JsDataHandler.java#L80
The error message could be more useful, but I'm not sure we can do much about this given that GWT seemingly doesn't support UTF-8 ( @niloc132  ?).

However, another issue I noticed - when importing this same file with deephaven-core using the `read_csv` function, it doesn't throw an error, but it gives the **wrong result**. The resulting table should be `穿仓保证金补偿`, but instead it just has `穿`. That could be dangerous, as the user may not know an error as occurred on import.

And the docs for `read_csv` seem to be out of data as well: https://deephaven.io/core/docs/reference/data-import-export/CSV/readCsv/
I'll file another ticket for that.

**Comment by kosak** [comment] 2022-10-08 00:03
I'm looking at the read_csv truncation situation.

**Comment by kosak** [comment] 2022-10-08 02:26
We have (at least) two different ways of getting CSVs into the system and it looks like this example tickled bugs in both of them. :smile:

The web UI is not my department, but for `read_csv` I have fixed the bug ( see https://github.com/deephaven/deephaven-csv/pull/71 ) and I expect it to make into our next release. See screenshot below!

I believe the explanation provided above is somewhat misleading and I'd like to humbly offer some clarifications.

UTF-8, UTF-16, and UTF-32 are different binary encodings for Unicode text, and they are all fully capable of representing all of Unicode. 

The file you attached to this bug report (errordata-short.csv) is in fact a UTF-8 file. There is no UTF-16 involvement here.

The characters in 穿仓保证金补偿 (U+7A7F, U+4ED3, U+4FDD, U+8BC1, and so on) could be said to be "16 bits" because they fall outside of ASCII, but the fact that `read_csv` choked on them was really just a careless typo on my part (the effective part of the bug fix is one line long  :smile: )

The fix reads the original `errordata.csv` file correctly (except it doesn't like the fact that the final line lacks a newline). When I add a newline, the file reads correctly. 

Screenshot!

![image](https://user-images.githubusercontent.com/720660/194682238-2c0bf5fd-3872-44f6-89d6-62e83696164f.png)

**Comment by mofojed** [comment] 2023-07-21 15:05
Looks like this is fixed in the latest:
```
Engine Version: 0.27.0
Web UI Version: 0.44.1
Java Version: 11.0.19
Barrage Version: 0.6.0
```

**Closed by mofojed** 2023-07-21 15:05 UTC
Labels: bug, web-client-ui, csv, user-reported
