### ISSUE TITLE
Support a Windowed table type

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#1089] opened 2021-08-19 19:46 UTC
This would be useful for Kafka ingestion among other things.  Kafka "append" table type has unbounded max memory requirements, which is undesirable in realistic in many production scenarios.

**Comment by cpwright** [comment] 2021-08-19 19:53
As a user I would like to maintain a bounded history of my Stream table (e.g. one ingested from Kafka).  For example, I may want to keep the last 15 minutes of data or alternatively the last million rows.  This will allow me to analyze recent events, without the unbounded memory utilization of an append table.

To store the data, we should use in-memory column sources and a rolling set of data blocks.

**Comment by rcaudy** [comment] 2021-08-19 20:01
Duplicate of https://github.com/deephaven/deephaven-core/issues/1054

**Closed by rcaudy** 2021-08-19 20:01 UTC
Labels: feature request, triage, NoDocumentationNeeded
