### ISSUE TITLE
Recent Python UDF change added a hard dependency of numba

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/deephaven-core#5133] opened 2024-02-09 01:15 UTC
Which makes experimenting DH with newer, not-yet-supported-by-numba Python versions almost impossible.

Related to #3082, which is more about test code's dependency on numba

**Comment by devinrsmith** [comment] 2024-02-09 01:45
potentially dupe of https://github.com/deephaven/deephaven-core/issues/3082

**Closed** 2024-02-22 03:48 UTC
Labels: bug, core, python, python-server-side
