### ISSUE TITLE
Snapshot does not work OOTB with static tables

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/deephaven-core#824] opened 2021-07-06 20:38 UTC
**Description**

The .snapshot() method does not freeze tables in time, as described in the enterprise docs [here](https://deephaven.io/enterprise/docs/onboarding/become-an-expert/use-table-snapshots/#creating-a-static-snapshot).

**Steps to reproduce**

Execute the following commands:

`from deephaven import TableTools as ttools`
`data = ttools.timeTable("00:00:10").update("X=i", "Y=new int[]{0,1,2}").tail(5).ungroup()`
`static_data = ttools.emptyTable(1).snapshot(data)`

**Expected results**

I expected `static_data` to contain exactly what `data` contained at the time of creating `static_data`, in a static table. You will get this desired result if you instead use

`static_data = ttools.emptyTable(1).snapshot(data, True)`

where this second optional parameter is not described anywhere in enterprise docs.

**Actual results**

`static_data` will be an empty table with the correct schema. No data from `data` gets copied.

**Versions**
 - Deephaven: 0.1.0
 - OS: masOS Big Sur 11.4
 - Browser: Safari 14.1.1
 - Docker: 3.3.3

**Comment by nbauernfeind** [comment] 2021-07-23 18:37
@rcaudy is there any reason not to ignore the initialSnapshot parameter if the left table is static?

If so is fixed as easily as:
```
diff --git a/DB/src/main/java/io/deephaven/db/v2/QueryTable.java b/DB/src/main/java/io/deephaven/db/v2/QueryTable.java
index 81cb37aba5..37939a881f 100644
--- a/DB/src/main/java/io/deephaven/db/v2/QueryTable.java
+++ b/DB/src/main/java/io/deephaven/db/v2/QueryTable.java
@@ -1860,7 +1860,7 @@ public class QueryTable extends BaseTable {
         final SnapshotInternalListener listener = new SnapshotInternalListener(this, lazySnapshot, tableToSnapshot,
                 result, resultLeftColumns, resultRightColumns, resultIndex);
 
-        if (doInitialSnapshot) {
+        if (!isRefreshing() || doInitialSnapshot) {
             if (!isRefreshing() && tableToSnapshot.isLive() && !lazySnapshot) {
                 // if we are making a static copy of the table, we must ensure that it does not change out from under us
                 ConstructSnapshot.callDataSnapshotFunction("snapshotInternal",
```

**Comment by nbauernfeind** [comment] 2021-07-24 00:01
@rcaudy pointed out that the behavior for static and non-static left tables should remain the same. For example, if you say wait for a tick, you probably know how to make that table tick (and it would be an error to use a static table).

This works as intended (maybe the default value should be to take a snapshot... but might be too late to change that). So, passing off to @chipkent to triage for fixing the documentation. I noticed the text is correct, but the sample result image does not match.

**Comment by nbauernfeind** [comment] 2021-07-24 02:46
Ryan / Charles and I all came to the same conclusion of changing the default for the variable. So I reassigned to me. PR Incoming.

**Comment by nbauernfeind** [comment] 2021-07-26 18:23
@chipkent The documentation needs to be updated. The default behavior of getting an initial snapshot is now true for both left static tables and left ticking tables. This is a deviation from DHE.

**Closed** 2021-07-26 21:00 UTC
Labels: DocumentationNeeded, bug, core, triage
