### ISSUE TITLE
subscribeToFieldUpdates does not list application fields when deephaven.console.disable is true

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#2779] opened 2022-08-30 15:45 UTC
**Description**

When `deephaven.console.disable` option is set to `true` (i.e. consoles are disabled), calling `subscribeToFieldUpdates` on the connection just returns an empty list instead of the objects created from an app.
Requires the functionality in PR #2773 .

**Steps to reproduce**
1. Add a startup script that creates some objects in /data/app.d/, e.g.:
```
➜  deephaven-core git:(596-no-console) cat data/app.d/firstApp.app
type=script
scriptType=python
enabled=true
id=hello.world
name=Hello World!
file_0=firstApp.py
➜  deephaven-core git:(596-no-console) cat data/app.d/firstApp.py 
from deephaven import empty_table, new_table, time_table
from deephaven.column import string_col, int_col, double_col

miami = new_table([
    string_col("Month",["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]),
    int_col("Temp", [60, 62, 65, 68, 73, 76, 77, 77, 76, 74, 68, 63]),
    double_col("Rain", [1.62, 2.25, 3.00, 3.14, 5.34, 9.67, 6.50, 8.88, 9.86, 6.33, 3.27, 2.04])
])

basic = empty_table(100).update(["A=i", "B=i-50", "C=i*i"])
```
2. Set `deephaven.console.disable` to `true` and start the server (I set it in the `ConsoleServiceGrpcImpl.java` and did prepareCompose/docker-compose up)
3. Navigate to http://localhost:10000/jsapi/ in the browser and open the browser console
4. Run the following command to subscribe to field updates:
```js
var connection = new dh.IdeConnection('http://localhost:10000')
connection.subscribeToFieldUpdates(updates => console.log('Got updates', updates))
```

**Expected results**
4. 'Got Updates' should be printed to console with an array of 2 items created

**Actual results**
4. 'Got Updates' is printed, but the array has 0 items

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: `c82278e1b55a9d8989d751c30ad5fc5b4528de9f`
 - OS: macOS Monterey 12.5.1
 - Browser: Version 104.0.5112.101 (Official Build) (arm64)

**Comment by niloc132** [comment] 2022-09-12 16:14
Closing as invalid - the problem is that this code is writing to global scope instead of writing to the application context. This is permitted when a script session is in use, since the script session will be directly exposed to the user, but if the user can't access the script session, those global variables likewise should not be accessible (and indeed, are not accessible, as designed).

Instead, the sample script must use the `deephaven.appmode` python module to write the scope that it needs. For example, 

```
from deephaven import empty_table, new_table, time_table
from deephaven.column import string_col, int_col, double_col

from deephaven.appmode import get_app_state

get_app_state()['miami'] = new_table([
    string_col("Month",["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]),
    int_col("Temp", [60, 62, 65, 68, 73, 76, 77, 77, 76, 74, 68, 63]),
    double_col("Rain", [1.62, 2.25, 3.00, 3.14, 5.34, 9.67, 6.50, 8.88, 9.86, 6.33, 3.27, 2.04])
])

get_app_state()['basic'] = empty_table(100).update(["A=i", "B=i-50", "C=i*i"])
```

**Closed by niloc132** 2022-09-12 16:14 UTC
Labels: bug, triage
