### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to view a table

### ISSUE THREAD

**Issue by devonpallison** [deephaven/deephaven-core#4577] opened 2023-09-29 21:44 UTC
**Description**

When I try to view a table created in a DnD persistent query, I get an exception and need to reload the panel.

**Steps to reproduce**
I created the table, FilteredSPTRolloverCompleteMerged, with this query:

[scratch_2.txt](https://github.com/deephaven/deephaven-core/files/12772120/scratch_2.txt)

**Expected results**

The table should be viewable without errors.

**Actual results**

My table's panel had an error message. I found this trace in the ProcessEventLog:
[error.txt](https://github.com/deephaven/deephaven-core/files/12772061/error.txt)

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: Community version 28.0, Enterprise Version 1.20230511.327

**Comment by rcaudy** [comment] 2023-10-04 19:18
I am reasonably sure that this has the same root cause as https://github.com/deephaven/deephaven-core/issues/4586. Will close this one as a duplicate.

**Closed by rcaudy** 2023-10-04 19:18 UTC
Labels: bug, query engine, core
