### ISSUE TITLE
Jetty shutdown deadlock

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#2490] opened 2022-06-07 19:11 UTC
I have very little information here, except that it appears to be called from shutdown, and that this instance was using jetty rather than jetty. We have seen other grpc-servlet deadlocks before (usually called by direct use of System.out/err from in an IO thread, interfering with the log stream to the browser), but while this is probably connected to a log stream to the browser, it doesn't _appear_ to be specific to the web socket's own error handling.

My quick impression is that the server was shutting down, so called SessionService.closeAllSessions(), which took the lock on `io.deephaven.util.datastructures.SimpleReferenceManager` to loop through its contents, and `BarrageMessageProducer` tried to write a log message, which tried to take a lock on `io.deephaven.io.logger.LogBufferInterceptor`.

At the same time, a log message was being written to the grpc client (holding a lock in `io.deephaven.io.logger.LogBufferInterceptor`), but an error occurred, and calling SessionClonableObserver.close() tried to take the lock on `io.deephaven.util.datastructures.SimpleReferenceManager`. 

Info from `jstack`:
```
Found one Java-level deadlock:
=============================
"CleanupReferenceProcessor-liveness-drainingThread":
  waiting to lock monitor 0x00007f5fd8007b00 (object 0x000000050f6f5020, a io.deephaven.io.logger.LogBufferInterceptor),
  which is held by "Thread-28"
"Thread-28":
  waiting to lock monitor 0x00007f5dd8626900 (object 0x0000000515ff3a78, a io.deephaven.util.datastructures.SimpleReferenceManager),
  which is held by "Thread-0"
"Thread-0":
  waiting to lock monitor 0x00007f5fd8007b00 (object 0x000000050f6f5020, a io.deephaven.io.logger.LogBufferInterceptor),
  which is held by "Thread-28"

Java stack information for the threads listed above:
===================================================
"CleanupReferenceProcessor-liveness-drainingThread":
        at io.deephaven.io.logger.LogBuffer.record(LogBuffer.java:46)
        - waiting to lock <0x000000050f6f5020> (a io.deephaven.io.logger.LogBufferInterceptor)
        at io.deephaven.logback.LogBufferAppender.append(LogBufferAppender.java:57)
        at io.deephaven.logback.LogBufferAppender.append(LogBufferAppender.java:15)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:50)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:272)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:259)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:423)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:385)
        at ch.qos.logback.classic.Logger.info(Logger.java:597)
        at io.deephaven.internal.log.LoggerSlf4j$Sink.write(LoggerSlf4j.java:156)
        at io.deephaven.internal.log.LoggerSlf4j$Sink.write(LoggerSlf4j.java:114)
        at io.deephaven.io.log.impl.LogEntryImpl.end(LogEntryImpl.java:78)
        at io.deephaven.internal.log.LoggerSlf4j$Entry.endl(LoggerSlf4j.java:99)
        at io.deephaven.engine.liveness.RetainedReferenceTracker.ensureReferencesDroppedInternal(RetainedReferenceTracker.java:191)
        at io.deephaven.engine.liveness.RetainedReferenceTracker.cleanup(RetainedReferenceTracker.java:172)
        at io.deephaven.util.reference.CleanupReferenceProcessor$DrainQueue.run(CleanupReferenceProcessor.java:116)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)
"Thread-28":
        at io.deephaven.server.session.SessionState.removeOnCloseCallback(SessionState.java:406)
        - waiting to lock <0x0000000515ff3a78> (a io.deephaven.util.datastructures.SimpleReferenceManager)
        at io.deephaven.server.session.SessionCloseableObserver.close(SessionCloseableObserver.java:26)
        at io.deephaven.server.console.ConsoleServiceGrpcImpl$LogBufferStreamAdapter.record(ConsoleServiceGrpcImpl.java:445)
        at io.deephaven.io.logger.LogBuffer.recordInternal(LogBuffer.java:39)
        - locked <0x000000050f6f5020> (a io.deephaven.io.logger.LogBufferInterceptor)
        at io.deephaven.io.logger.LogBuffer.record(LogBuffer.java:46)
        - locked <0x000000050f6f5020> (a io.deephaven.io.logger.LogBufferInterceptor)
        at io.deephaven.logback.LogBufferAppender.append(LogBufferAppender.java:57)
        at io.deephaven.logback.LogBufferAppender.append(LogBufferAppender.java:15)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:50)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:272)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:259)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:423)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:385)
        at ch.qos.logback.classic.Logger.info(Logger.java:597)
        at io.deephaven.internal.log.LoggerSlf4j$Sink.write(LoggerSlf4j.java:156)
        at io.deephaven.internal.log.LoggerSlf4j$Sink.write(LoggerSlf4j.java:114)
        at io.deephaven.io.log.impl.LogEntryImpl.end(LogEntryImpl.java:78)
        at io.deephaven.internal.log.LoggerSlf4j$Entry.endl(LoggerSlf4j.java:99)
        at io.deephaven.server.table.ExportedTableUpdateListener.onCompleted(ExportedTableUpdateListener.java:111)
        - locked <0x0000000515feedc8> (a io.deephaven.server.table.ExportedTableUpdateListener)
        at io.deephaven.server.session.SessionState$ExportListener$$Lambda$1473/0x0000000800992c40.run(Unknown Source)
        at io.deephaven.extensions.barrage.util.GrpcUtil.safelyExecuteLocked(GrpcUtil.java:155)
        - locked <0x0000000515feedc8> (a io.deephaven.server.table.ExportedTableUpdateListener)
        at io.deephaven.server.session.SessionState$ExportListener.onRemove(SessionState.java:1121)
        at io.deephaven.server.session.SessionState.removeExportListener(SessionState.java:1027)
        at io.deephaven.server.table.TableServiceGrpcImpl.lambda$exportedTableUpdates$7(TableServiceGrpcImpl.java:335)
        at io.deephaven.server.table.TableServiceGrpcImpl$$Lambda$720/0x000000080061d040.run(Unknown Source)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onCancel(ServerCalls.java:195)
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:362)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:350)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:913)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closedInternal(ServerImpl.java:920)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.closed(ServerImpl.java:887)
        at io.grpc.internal.AbstractServerStream$TransportState.closeListener(AbstractServerStream.java:332)
        at io.grpc.internal.AbstractServerStream$TransportState.transportReportStatus(AbstractServerStream.java:276)
        at io.grpc.servlet.web.websocket.WebsocketStreamImpl.transportReportStatus(WebsocketStreamImpl.java:127)
        at io.grpc.servlet.web.websocket.WebSocketServerStream.onError(WebSocketServerStream.java:133)
        at java.lang.invoke.DirectMethodHandle$Holder.invokeVirtual(java.base@11.0.15/DirectMethodHandle$Holder)
        at java.lang.invoke.LambdaForm$MH/0x00000008005c5440.invoke(java.base@11.0.15/LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/0x00000008005d2040.invoke_MT(java.base@11.0.15/LambdaForm$MH)
        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onError(JakartaWebSocketFrameHandler.java:312)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$closeConnection$2(WebSocketCoreSession.java:283)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$$Lambda$692/0x00000008005d4440.run(Unknown Source)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1460)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1479)
        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.closeConnection(WebSocketCoreSession.java:283)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$sendFrame$7(WebSocketCoreSession.java:518)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$$Lambda$1322/0x0000000800938840.run(Unknown Source)
        at org.eclipse.jetty.util.Callback$3.succeeded(Callback.java:155)
        at org.eclipse.jetty.websocket.core.internal.TransformingFlusher.notifyCallbackSuccess(TransformingFlusher.java:151)
        at org.eclipse.jetty.websocket.core.internal.TransformingFlusher$Flusher.process(TransformingFlusher.java:111)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:214)
        at org.eclipse.jetty.websocket.core.internal.TransformingFlusher.sendFrame(TransformingFlusher.java:75)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.sendFrame(WebSocketCoreSession.java:521)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.close(WebSocketCoreSession.java:239)
        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.processHandlerError(WebSocketCoreSession.java:370)
        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onIdleExpired(WebSocketConnection.java:233)
        at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407)
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
        at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:108)
        at org.eclipse.jetty.io.IdleTimeout.activate(IdleTimeout.java:131)
        at org.eclipse.jetty.io.IdleTimeout.setIdleTimeout(IdleTimeout.java:95)
        at org.eclipse.jetty.server.AbstractConnector.shutdown(AbstractConnector.java:390)
        at org.eclipse.jetty.server.AbstractNetworkConnector.shutdown(AbstractNetworkConnector.java:99)
        at org.eclipse.jetty.util.component.Graceful$$Lambda$1467/0x0000000800994040.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(java.base@11.0.15/ReferencePipeline.java:195)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@11.0.15/ArrayList.java:1655)
        at java.util.stream.AbstractPipeline.copyInto(java.base@11.0.15/AbstractPipeline.java:484)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@11.0.15/AbstractPipeline.java:474)
        at java.util.stream.AbstractPipeline.evaluate(java.base@11.0.15/AbstractPipeline.java:550)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(java.base@11.0.15/AbstractPipeline.java:260)
        at java.util.stream.ReferencePipeline.toArray(java.base@11.0.15/ReferencePipeline.java:517)
        at org.eclipse.jetty.util.component.Graceful.shutdown(Graceful.java:146)
        at org.eclipse.jetty.server.Server.doStop(Server.java:489)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at io.deephaven.server.jetty.JettyBackedGrpcServer.lambda$stopWithTimeout$1(JettyBackedGrpcServer.java:111)
        at io.deephaven.server.jetty.JettyBackedGrpcServer$$Lambda$1466/0x0000000800994c40.run(Unknown Source)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)
"Thread-0":
        at io.deephaven.io.logger.LogBuffer.record(LogBuffer.java:46)
        - waiting to lock <0x000000050f6f5020> (a io.deephaven.io.logger.LogBufferInterceptor)
        at io.deephaven.logback.LogBufferAppender.append(LogBufferAppender.java:57)
        at io.deephaven.logback.LogBufferAppender.append(LogBufferAppender.java:15)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:50)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:272)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:259)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:423)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:385)
        at ch.qos.logback.classic.Logger.info(Logger.java:597)
        at io.deephaven.internal.log.LoggerSlf4j$Sink.write(LoggerSlf4j.java:156)
        at io.deephaven.internal.log.LoggerSlf4j$Sink.write(LoggerSlf4j.java:114)
        at io.deephaven.io.log.impl.LogEntryImpl.end(LogEntryImpl.java:78)
        at io.deephaven.internal.log.LoggerSlf4j$Entry.endl(LoggerSlf4j.java:99)
        at io.deephaven.server.barrage.BarrageMessageProducer.lambda$removeSubscription$4(BarrageMessageProducer.java:629)
        at io.deephaven.server.barrage.BarrageMessageProducer$$Lambda$1318/0x000000080091c840.accept(Unknown Source)
        at io.deephaven.server.barrage.BarrageMessageProducer.lambda$findAndUpdateSubscription$2(BarrageMessageProducer.java:578)
        at io.deephaven.server.barrage.BarrageMessageProducer$$Lambda$1319/0x000000080091cc40.apply(Unknown Source)
        at io.deephaven.server.barrage.BarrageMessageProducer.findAndUpdateSubscription(BarrageMessageProducer.java:593)
        - locked <0x0000000519aa2aa0> (a io.deephaven.server.barrage.BarrageMessageProducer)
        at io.deephaven.server.barrage.BarrageMessageProducer.removeSubscription(BarrageMessageProducer.java:626)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoExchangeMarshaller$SubscriptionRequestHandler.close(ArrowFlightUtil.java:712)
        - locked <0x0000000519aa2d00> (a io.deephaven.server.arrow.ArrowFlightUtil$DoExchangeMarshaller$SubscriptionRequestHandler)
        at io.deephaven.server.arrow.ArrowFlightUtil$DoExchangeMarshaller.close(ArrowFlightUtil.java:447)
        at io.deephaven.server.session.SessionState.lambda$onExpired$0(SessionState.java:447)
        at io.deephaven.server.session.SessionState$$Lambda$1476/0x0000000800992440.accept(Unknown Source)
        at io.deephaven.util.datastructures.SimpleReferenceManager.forEach(SimpleReferenceManager.java:133)
        at io.deephaven.server.session.SessionState.onExpired(SessionState.java:445)
        - locked <0x0000000515ff3a78> (a io.deephaven.util.datastructures.SimpleReferenceManager)
        at io.deephaven.server.session.SessionService.closeAllSessions(SessionService.java:266)
        at io.deephaven.server.session.SessionService.onShutdown(SessionService.java:122)
        - locked <0x000000050fb9fd00> (a io.deephaven.server.session.SessionService)
        at io.deephaven.server.runner.DeephavenApiServer$$Lambda$258/0x00000008002c2c40.invoke(Unknown Source)
        at io.deephaven.util.process.ShutdownManagerImpl.lambda$maybeInvokeTasks$2(ShutdownManagerImpl.java:108)
        at io.deephaven.util.process.ShutdownManagerImpl$$Lambda$1465/0x0000000800994840.accept(Unknown Source)
        at java.util.Map.forEach(java.base@11.0.15/Map.java:661)
        at java.util.Collections$UnmodifiableMap.forEach(java.base@11.0.15/Collections.java:1505)
        at io.deephaven.util.process.ShutdownManagerImpl.maybeInvokeTasks(ShutdownManagerImpl.java:103)
        at io.deephaven.util.process.ShutdownManagerImpl$$Lambda$77/0x000000080016f040.run(Unknown Source)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

Found 1 deadlock.
```

**Comment by nbauernfeind** [comment] 2022-06-07 19:58
This looks like a duplicate of #2086. I will prioritize a fix.

**Closed** 2022-06-07 19:58 UTC
Labels: bug, session
