### ISSUE TITLE
History panel in the web UI black/not refreshing.

### ISSUE THREAD

**Issue by jcferretti** [deephaven/deephaven-core#963] opened 2021-08-03 17:01 UTC
See attached images for a sequence of operations (before/after) that leaves my history panel black.
![before](https://user-images.githubusercontent.com/37232625/128056221-8bc22504-89a9-44f4-b8e4-34369adf4406.png)
![after](https://user-images.githubusercontent.com/37232625/128056250-ec1a3a46-b419-4381-b2f4-6e07900d3c76.png)

**Comment by mofojed** [comment] 2022-10-07 14:37
Without any further logs, I am guessing the root cause is command history being slow when there are thousands of items: https://github.com/deephaven/web-client-ui/issues/325

Closing this ticket in favour of the web-client-ui#325

**Closed by mofojed** 2022-10-07 14:37 UTC
Labels: bug
