### ISSUE TITLE
Calling update() on a blink table makes it no longer a blink table

### ISSUE THREAD

**Issue by devonpallison** [deephaven/deephaven-core#4997] opened 2023-12-29 21:26 UTC
**Description**

Calling update() on a blink table makes it lose the blink table attribute.

**Steps to reproduce**
Create a blink table:

`t = KafkaTools.consumeToTable(createProps(),
            "protoTopic",
            {x -> x == 1},
            KafkaTools.ALL_PARTITIONS_DONT_SEEK,
            KafkaTools.FROM_PROPERTIES,
            KafkaTools.Consume.protobufSpec(options),
            KafkaTools.TableType.blink())`
Call update on the result
`t2 = t.update("X = 5")`
**Expected results**
The result is still a blink table.

**Actual results**
The result is no longer a blink table:
![image](https://github.com/deephaven/deephaven-core/assets/62663619/d23b062a-3128-4214-8a3e-217f4ac14c70)

**Comment by niloc132** [comment] 2023-12-29 21:31
Slightly simpler case that also shows the bug:
```python
from deephaven import time_table
t = time_table("PT1s", blink_table=True)
print(t.attributes()) # Expected, shows BlinkTable: True
print(t.update("I=1").attributes())# Bug, shows empty
```
Contrast with an add-only table:
```python
from deephaven import time_table
t = time_table("PT1s")
print(t.attributes()) # Expected, shows AddOnly: True, AppendOnly: True
print(t.update("I=1").attributes())# Correct, shows the same
```

**Comment by rcaudy** [comment] 2023-12-29 22:50
Duplicate of https://github.com/deephaven/deephaven-core/issues/2474

**Closed by rcaudy** 2023-12-29 22:50 UTC
Labels: bug, triage
