### ISSUE TITLE
IDE hangs with partial results after Groovy error

### ISSUE THREAD

**Issue by mikeblas** [deephaven/deephaven-core#884] opened 2021-07-21 22:06 UTC
For a bit, we had some bogus Groovy code in the "getting started" tutorial.  Here's the bogus code:

```groovy
left = newTable(
        stringCol("LastName", "Rafferty", "Jones", "Steiner", "Robins", "Smith", "Rogers"),
        intCol("DeptID", 31, 33, 33, 34, 34, NULL_INT),
        stringCol("Telephone", "(347) 555-0123", "(917) 555-0198", "(212) 555-0167", "(952) 555-0110", None, None)
    )

right = newTable(
        intCol("DeptID", 31, 33, 34, 35),
        stringCol("DeptName", "Sales", "Engineering", "Clerical", "Marketing"),
        stringCol("Telephone", "(646) 555-0134", "(646) 555-0178", "(646) 555-0159", "(212) 555-0111")
    )

t = left.join(right, "DeptID", "DeptName,DeptTelephone=Telephone")
```

The problem is that someone had a Python moment and used "None" instead of "null".

Easy enough! Here's the fixed code, with "null" as Groovy expects.

```groovy
left = newTable(
        stringCol("LastName", "Rafferty", "Jones", "Steiner", "Robins", "Smith", "Rogers"),
        intCol("DeptID", 31, 33, 33, 34, 34, NULL_INT),
        stringCol("Telephone", "(347) 555-0123", "(917) 555-0198", "(212) 555-0167", "(952) 555-0110", null, null)
    )

right = newTable(
        intCol("DeptID", 31, 33, 34, 35),
        stringCol("DeptName", "Sales", "Engineering", "Clerical", "Marketing"),
        stringCol("Telephone", "(646) 555-0134", "(646) 555-0178", "(646) 555-0159", "(212) 555-0111")
    )

t = left.join(right, "DeptID", "DeptName,DeptTelephone=Telephone")
```

We expect the bad code to cause an error. That's fine. But after it does, pasting the good code causes the IDE to not render the results. It shows a swirling DH logo and a Cancel button. The Cancel button doesn't work. You can repro like this:

1. Start up DH Core with the Groovy environment: `docker-compose --env-file default_groovy.env up`
2. Connect your browser.  Switch to "Groovy" with the dropdown menu.
3. paste the bad code with "None".
4. Get an error.
5. paste the good code with "null".
6. It hangs with the broken CANCEL button and swirling logo.
7. Kill everything. Restart.
8. Paste the good code with "null".
9. It works!

![image](https://user-images.githubusercontent.com/6632219/126566238-95354354-1865-4ab7-b2f0-ef5551d47795.png)

**Comment by mofojed** [comment] 2021-07-22 14:24
I am unable to reproduce with these steps provided - the table loads fine for me after the command executes.

However, from the description, this sounds like #834 , which could be verified if we capture network logs of this in action. @mikeblas is this consistently reproducible with the steps provided above? Which browser are you using?

**Comment by mikeblas** [comment] 2021-07-22 14:33
Reproduced three out of three times for me yesterday.  I'm using Firefox; everything is in an Ubuntu 20 LTS VM.

**Comment by mofojed** [comment] 2021-07-22 14:34
I was able to reproduce by running the commands multiple times in a row. Preliminary analysis shows the same root cause as #834

**Comment by mofojed** [comment] 2021-07-22 14:51
Looking at the Network logs, for some reason there's over a minute delay after executing the command before the filter command is executed.

![image](https://user-images.githubusercontent.com/4505624/126658316-c27bb2c3-2ace-4608-a4cb-472e35b12a2c.png)

In another more succinct example, this screenshot below shows the Batch command not being sent for ~10s after the applyFilter/setViewport commands are called in the API, it should be sent pretty much immediately. @nbauernfeind should take a look:

![image](https://user-images.githubusercontent.com/4505624/126659291-40ddfcd7-24c7-4c2d-a838-c2949abb99b6.png)

**Comment by mofojed** [comment] 2021-07-22 14:53
@mikeblas Could you try Chromium as well to see if this issue is reproducible there? I can only reproduce in Firefox.

**Comment by mofojed** [comment] 2021-08-09 13:44
Closing this one as a duplicate of #834 , @mikeblas can try and re-open if this is reproducible in Chrome/Chromium.

**Closed by mofojed** 2021-08-09 13:44 UTC
Labels: bug, triage
