### ISSUE TITLE
Flight RPC authorization wiring

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#4133] opened 2023-07-05 19:48 UTC
Just as we wrap all of our own service implementations with authorization hooks, we should provide the same level of granularity for other services we provide - namely, Flight RPCs. This would give us the ability to cut-off DoPut (or other Flight RPC requests) at a high level.

(Somewhat related to publishing concerns that are going to be solved at a lower-layer in https://github.com/deephaven/deephaven-core/pull/4101)

**Comment by nbauernfeind** [comment] 2023-07-11 15:36
This is a duplicate of #3146.

**Closed by nbauernfeind** 2023-07-11 15:36 UTC
Labels: feature request, grpc, authorization
