### ISSUE TITLE
Tag commits in deephaven-base-images repo in line with DHC releases

### ISSUE THREAD

**Issue by rbasralian** [deephaven/deephaven-core#5071] opened 2024-01-24 22:10 UTC
It would be helpful if deephaven-base-images were versioned alongside deephaven-core.

(Discussion in Slack [here](https://illumon.slack.com/archives/G01K6UHJ00K/p1705528101131399).)

**Comment by devinrsmith** [comment] 2024-01-24 23:15
The intention here is to be able to get cpp-client specifc build information from https://github.com/deephaven/deephaven-core/blob/main/cpp-client/README.md into an easier to understand state. Right now for example, it shows:

>Download build-dependencies.sh directly from https://github.com/deephaven/deephaven-base-images/raw/0f2c39f142140601b92d69a8fe8ee0c49b76ec7b/cpp-client/build-dependencies.sh

From customer perspective, it might be easier to line up version numbers, and download from something like:

>Download build-dependencies.sh directly from https://github.com/deephaven/deephaven-base-images/raw/vX.Y.Z-cpp-client/cpp-client/build-dependencies.sh

Note: in this theoretical example, the tag is `v.X.Y.Z-cpp-client`, as the different images that the deephaven-core release is based on can come from different underlying deephaven-base-images repo shas.

**Comment by devinrsmith** [comment] 2024-01-24 23:18
From a given deephaven-core commit, the corresponding SHA can be figured out via:

```sh
docker buildx imagetools inspect $(./gradlew -q docker-cpp-clients-multi-base:showImageId) --format "{{ json .Provenance.SLSA.metadata }}" | jq -r '."https://mobyproject.org/buildkit@v1#metadata".vcs.revision'
```

This step could be used as part of the deephaven-core release process to tag the correct commit from deephaven-base-images.

**Comment by devinrsmith** [comment] 2024-01-24 23:22
We could also have the link always point to the *latest* release, if we think that would be helpful, but then give users the tag if they need a specific version (that would aid us from having to manually update this README with every cpp-clients-multi-base bump...)

**Comment by jcferretti** [comment] 2024-01-25 03:01
I don't see how this actually helps.  build-dependencies.sh changes between releases, frequently that has happened more than once.  Even if it didn't, the point in time it changes is never exactly at a release; we need to keep README.md URL consistent with the version of build-dependencies.sh used in the image.  There is no tag for an in-between-releases point.  So what is the actual proposal here?  We continue what we do now (PR changes make README.md URL pointing to specific SHA), and then on a release README.md is modified to point to a tagged version?

**Comment by jcferretti** [comment] 2024-01-25 03:15
> We could also have the link always point to the latest release
We can't.  At /any/ time, the README.md needs to point to the right version of build-dependencies.sh to use with the source.

If we take 3 steps back and actually look at this, the issue is that we need a manual change in the README.md file with a modification to the right version.  This is done manually, and any changes that we could (I don't think we can, correctly) do with tags will do the same.

Since is a manual change (edit) that needs to happen every and any time build-dependencies.sh changes, wouldn't it be much much simpler to just have the manual change to be to /copy/ build-dependencies.sh to the deephaven-core repository so that the README.md file can point to a file in the same repo?  That file wouldn't be used in any other way, and copying a file at first "feels" wrong since it is duplicity, but this is not more duplicity than, eg, having the output of proto files checked in.  And is much more user friendly, and is simpler as a step for a developer to do:  A developer that is testing changes to build-dependencies.sh and has been creates images to test and finally is ready to commit them, has the right file at hand much more readily than a link to its version (believe me, I've done this scores of times).

**Comment by devinrsmith** [comment] 2024-01-30 16:50
Resolved by https://github.com/deephaven/deephaven-core/pull/5072

**Closed by devinrsmith** 2024-01-30 16:50 UTC
Labels: feature request, core, ci
