### ISSUE TITLE
Rollup tables sometimes do not expand or collapse correctly

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#3398] opened 2023-02-02 14:40 UTC
**Description**

If you build a rollup table, sometimes when you expand/collapse rows it doesn't work. UI seems to be sending the expand command correctly and receives an update from the table, but the state of the table hasn't actually changed.

**Steps to reproduce**
1. Run the following snippet to create a random table:
```
from deephaven import empty_table, time_table

size = 100
scale = 1000

random_values_with_null_NaN = empty_table(size).update([
    "MyString=(i%11==0? null : `a`+(int)(scale*(Math.random()*2-1)))",
    "MyInt=(i%12==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyLong=(i%13==0 ? null : (long)(scale*(Math.random()*2-1)))",
    "MyFloat=(float)(i%14==0 ? null : i%10==0 ? 1.0F/0.0F: i%5==0 ? -1.0F/0.0F : (float) scale*(Math.random()*2-1))",
    "MyDouble=(double)(i%16==0 ? null : i%10==0 ? 1.0D/0.0D: i%5==0 ? -1.0D/0.0D : (double) scale*(Math.random()*2-1))",
    "MyBoolean = (i%17==0 ? null : (int)(10*Math.random())%2==0)",
    "MyChar = (i%18==0 ? null : new Character((char) (((26*Math.random())%26)+97)) )",
    "MyShort=(short)(i%19==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyByte=(Byte)(i%19==0 ? null : new Byte( Integer.toString((int)(Byte.MAX_VALUE*(Math.random()*2-1)))))",
    "MyBigDecimal=(i%21==0 ? null : new java.math.BigDecimal(scale*(Math.random()*2-1)))",
    "MyBigInteger=(i%22==0 ? null : new java.math.BigInteger(Integer.toString((int)(scale*(Math.random()*2-1)))))"
])
```
2. From the table side bar, select Rollup Rows, and double click the `MyBoolean` and `MyChar` columns to group by them
3. Using the mouse, expand the `null` section, then the `false` section, and then the `true` section (see video)

**Expected results**
3. All sections should be expanded

**Actual results**
3. The `true` section does not expand. If you keep clicking a bunch of times, it eventually expands

**Additional details and attachments**

No errors in the logs.

![rollup-table-expand](https://user-images.githubusercontent.com/4505624/216354676-071220b8-d86b-4c39-92fa-ebc1715f3c52.gif)

**Versions**
Engine Version: 0.21.0
Web UI Version: 0.28.0
Java Version: 17.0.6
Barrage Version: 0.5.0

**Comment by niloc132** [comment] 2023-02-02 21:02
Duplicate of https://github.com/deephaven/deephaven-core/issues/3347

**Closed by niloc132** 2023-02-02 21:02 UTC
Labels: bug, triage
